### ISSUE TITLE
FR6.  Run RX Dispensing Report 

### ISSUE THREAD

**Issue by er0531** [adwait97/medManager#7]
Goal: The system will generate a report of prescription   item medication dispensed

Stakeholders: Pharmacy manager

Description: The system will generate a   report of prescription items through a given time. This will help the user   keep track of what medication was dispensed through a given time to minimize   any error.

Origin: Team member came up with this first meeting

Version: 1.0

Date: 05/21/20

Priority: 1

**Comment by adwait97** [comment]
completed through showReports
